#!/usr/bin/env python3
"""Generate the per-run Renode platform and peripheral scripts.

Renode resolves paths in .repl files relative to its own installation root, not
to the working directory, so the platform file is generated with absolute paths
rather than shipped static. Generating it also gives us the one hook we need for
the campaign runner: baking a seed into the sensor peripheral.

Invariant this file exists to protect: the seed reaches the *recording* side
only. Nothing downstream of the trace ever reads it.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SENSOR_SRC = REPO / "renode" / "sensor.py"
DEFAULT_OUT = REPO / "build" / "gen"

PLATFORM_TEMPLATE = """// GENERATED by tools/gen_run.py - do not edit.
// Seed for this run: {seed}

using "platforms/boards/stm32f4_discovery.repl"

// The stock STM32F4 model has no DWT block, so the recorder would have no
// timestamp source. CYCCNT is what every trace entry is stamped with.
dwt: Miscellaneous.DWT @ sysbus 0xE0001000
    frequency: 168000000

// The simulated world: two registers the firmware cannot predict. Two separate
// peripherals rather than one with two offsets, so the oracle's read hooks bind
// per register - Renode's peripheral-read hook exposes `value`, not `offset`.
// Seeded, so runs differ from one another on purpose: recording inside a
// deterministic simulator and replaying in the same one would prove nothing.
sensor: Python.PythonPeripheral @ sysbus 0x50000000
    size: 0x4
    initable: true
    filename: "{sensor_path}"

jitter: Python.PythonPeripheral @ sysbus 0x50000004
    size: 0x4
    initable: true
    filename: "{jitter_path}"
"""


def render_sensor(seed: int, role: str) -> str:
    src = SENSOR_SRC.read_text(encoding="utf-8")
    for pattern, replacement in (
        (r"^SEED = .*$", f"SEED = {seed}"),
        (r"^ROLE = .*$", f"ROLE = {role!r}"),
    ):
        src, count = re.subn(pattern, replacement, src, count=1, flags=re.MULTILINE)
        if count != 1:
            raise SystemExit(
                f"{SENSOR_SRC}: expected exactly one line matching {pattern!r}, "
                f"found {count}"
            )
    _require_ascii(SENSOR_SRC, src)
    return src


def _require_ascii(source: pathlib.Path, text: str) -> None:
    """Renode runs peripheral scripts under IronPython, which follows Python 2
    rules and refuses non-ASCII source. A stray em dash in a comment fails the
    whole platform at machine-creation time with an error that points at the
    generated file rather than the one you edited, so it is caught here."""
    try:
        text.encode("ascii")
    except UnicodeEncodeError as exc:
        offending = text[exc.start : exc.end]
        line = text.count("\n", 0, exc.start) + 1
        raise SystemExit(
            f"{source}:{line}: non-ASCII character {offending!r}. "
            "Renode's IronPython rejects it; keep peripheral scripts ASCII-only."
        ) from exc


# Renode monitor scripts comment with '#'. The '//' form belongs to .repl
# platform files; using it here aborts the whole include with a tokenizer error
# and leaves you with a machine that was never created.
RESC_TEMPLATE = """# GENERATED by tools/gen_run.py - do not edit.
# Seed for this run: {seed}
mach create "rewind-m-{seed}"
machine LoadPlatformDescription @{platform}
sysbus LoadELF @{elf}
sysbus.usart2 CreateFileBackend @{uart_out}
{oracle}emulation RunFor "{run_for}"
quit
"""

# Ground-truth recording, from outside the CPU. Renode hooks take a single line
# of Python, and three separate constraints shape what that line may contain:
#
#   - No backslashes. The monitor tokenises the line before Python sees it, and
#     an escape would not survive; chr(10) instead of a newline escape.
#   - No semicolons. The monitor splits commands on them even inside quotes, so
#     the usual `f=open(...); f.write(...); f.close()` idiom would be chopped
#     into three broken commands. Hence `with`.
#   - The file must be closed explicitly. IronPython finalises through the .NET
#     GC rather than by reference counting, so `open(...).write(...)` leaves the
#     handle unreferenced but unflushed: the file gets created and stays empty.
#     That failure is silent, parses cleanly as zero events, and cost two CI
#     rounds to find.
#
# Opening the file per event is not fast. It does not need to be: a run produces
# a few hundred events, and the oracle is not the thing whose cost is measured.
ORACLE_TEMPLATE = """# Ground truth for the differential check - see docs/TRACE-FORMAT.md
sysbus SetHookAfterPeripheralRead sysbus.sensor "with open(r'{oracle_out}','a') as f: f.write('S %d' % value + chr(10))"
sysbus SetHookAfterPeripheralRead sysbus.jitter "with open(r'{oracle_out}','a') as f: f.write('J %d' % value + chr(10))"
sysbus.cpu AddHookAtInterruptBegin "with open(r'{oracle_out}','a') as f: f.write('I %d' % exceptionIndex + chr(10))"
sysbus.cpu AddHookAtInterruptBegin "with open(r'{diag_out}','w') as f: f.write(' '.join(sorted(dir())) + chr(10))"
sysbus.cpu AddHookAtInterruptBegin "with open(r'{insn_out}','w') as f: f.write(str(self.ExecutedInstructions))"
"""

DEFAULT_ELF = REPO / "firmware" / "build" / "rewind-m.elf"


def generate(seed: int, out_dir: pathlib.Path) -> pathlib.Path:
    out_dir.mkdir(parents=True, exist_ok=True)

    sensor_path = out_dir / f"sensor_{seed}.py"
    sensor_path.write_text(render_sensor(seed, "sensor"), encoding="utf-8")

    jitter_path = out_dir / f"jitter_{seed}.py"
    jitter_path.write_text(render_sensor(seed, "jitter"), encoding="utf-8")

    platform_path = out_dir / f"rewind_{seed}.repl"
    platform_path.write_text(
        PLATFORM_TEMPLATE.format(
            seed=seed,
            # Forward slashes work on both platforms; backslashes would need
            # escaping inside the .repl string literal.
            sensor_path=sensor_path.as_posix(),
            jitter_path=jitter_path.as_posix(),
        ),
        encoding="utf-8",
    )
    return platform_path


def generate_resc(
    seed: int,
    out_dir: pathlib.Path,
    uart_out: pathlib.Path,
    run_for: str = "0.5",
    elf: pathlib.Path | None = None,
    oracle_out: pathlib.Path | None = None,
) -> pathlib.Path:
    """Emit a headless run script for one seed.

    Used by the campaign runner, which needs thousands of runs and cannot pay
    Robot Framework's per-suite startup cost.
    """
    # Every path in the script is made absolute. Renode resolves `@path` against
    # its own installation root rather than the working directory, so a relative
    # path here silently points somewhere nobody intended.
    out_dir = out_dir.resolve()
    platform_path = generate(seed, out_dir).resolve()
    elf_path = (elf or DEFAULT_ELF).resolve()
    if not elf_path.exists():
        raise SystemExit(f"{elf_path}: not built. Run `make -C firmware` first.")

    oracle_block = ""
    if oracle_out is not None:
        resolved = oracle_out.resolve()
        oracle_block = ORACLE_TEMPLATE.format(
            oracle_out=resolved.as_posix(),
            # Written with 'w' so it keeps only the last invocation: one line
            # naming what is actually in scope inside an interrupt hook. Renode's
            # own examples never use a variable there, so rather than guess at
            # `exceptionIndex` and get an empty trace again, the run reports it.
            diag_out=resolved.with_suffix(".names").as_posix(),
            # Instruction count as of the last recorded event, written through
            # the one mechanism already proven to work here. `echo` is not a
            # monitor command, which is how the previous attempt failed, and
            # the count this produces is the better denominator anyway: it
            # excludes the trace flush, which is not part of recording.
            insn_out=resolved.with_suffix(".insn").as_posix(),
        )

    resc_path = out_dir / f"run_{seed}.resc"
    resc_path.write_text(
        RESC_TEMPLATE.format(
            seed=seed,
            platform=platform_path.as_posix(),
            elf=elf_path.as_posix(),
            uart_out=uart_out.resolve().as_posix(),
            run_for=run_for,
            oracle=oracle_block,
        ),
        encoding="utf-8",
    )
    return resc_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--out-dir", type=pathlib.Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    platform_path = generate(args.seed, args.out_dir)
    print(platform_path.as_posix())
    return 0


if __name__ == "__main__":
    sys.exit(main())
