#!/usr/bin/env python3
"""Generate the per-run Renode platform and peripheral scripts.

Renode resolves paths in .repl files relative to its own installation root, not
to the working directory, so the platform file is generated with absolute paths
rather than shipped static. Generating it also gives us the one hook we need for
the campaign runner: baking a seed into the sensor peripheral.

Invariant this file exists to protect: the seed reaches the *recording* side
only. Nothing downstream of the trace ever reads it.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SENSOR_SRC = REPO / "renode" / "sensor.py"
DEFAULT_OUT = REPO / "build" / "gen"

PLATFORM_TEMPLATE = """// GENERATED by tools/gen_run.py - do not edit.
// Seed for this run: {seed}

using "platforms/boards/stm32f4_discovery.repl"

// The stock STM32F4 model has no DWT block, so the recorder would have no
// timestamp source. CYCCNT is what every trace entry is stamped with.
dwt: Miscellaneous.DWT @ sysbus 0xE0001000
    frequency: 168000000

// Depth sensor. On real hardware this address would be an ADC data register;
// here it is a seeded PRNG so that runs differ from one another on purpose.
sensor: Python.PythonPeripheral @ sysbus 0x50000000
    size: 0x4
    initable: true
    filename: "{sensor_path}"
"""


def render_sensor(seed: int) -> str:
    src = SENSOR_SRC.read_text(encoding="utf-8")
    patched, count = re.subn(
        r"^SEED = .*$", f"SEED = {seed}", src, count=1, flags=re.MULTILINE
    )
    if count != 1:
        raise SystemExit(
            f"{SENSOR_SRC}: expected exactly one 'SEED = ...' line, found {count}"
        )
    _require_ascii(SENSOR_SRC, patched)
    return patched


def _require_ascii(source: pathlib.Path, text: str) -> None:
    """Renode runs peripheral scripts under IronPython, which follows Python 2
    rules and refuses non-ASCII source. A stray em dash in a comment fails the
    whole platform at machine-creation time with an error that points at the
    generated file rather than the one you edited, so it is caught here."""
    try:
        text.encode("ascii")
    except UnicodeEncodeError as exc:
        offending = text[exc.start : exc.end]
        line = text.count("\n", 0, exc.start) + 1
        raise SystemExit(
            f"{source}:{line}: non-ASCII character {offending!r}. "
            "Renode's IronPython rejects it; keep peripheral scripts ASCII-only."
        ) from exc


def generate(seed: int, out_dir: pathlib.Path) -> pathlib.Path:
    out_dir.mkdir(parents=True, exist_ok=True)

    sensor_path = out_dir / f"sensor_{seed}.py"
    sensor_path.write_text(render_sensor(seed), encoding="utf-8")

    platform_path = out_dir / f"rewind_{seed}.repl"
    platform_path.write_text(
        PLATFORM_TEMPLATE.format(
            seed=seed,
            # Forward slashes work on both platforms; backslashes would need
            # escaping inside the .repl string literal.
            sensor_path=sensor_path.as_posix(),
        ),
        encoding="utf-8",
    )
    return platform_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--out-dir", type=pathlib.Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    platform_path = generate(args.seed, args.out_dir)
    print(platform_path.as_posix())
    return 0


if __name__ == "__main__":
    sys.exit(main())
