#!/usr/bin/env python3
"""Generate the per-run Renode platform and peripheral scripts.

Renode resolves paths in .repl files relative to its own installation root, not
to the working directory, so the platform file is generated with absolute paths
rather than shipped static. Generating it also gives us the one hook we need for
the campaign runner: baking a seed into the sensor peripheral.

Invariant this file exists to protect: the seed reaches the *recording* side
only. Nothing downstream of the trace ever reads it.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SENSOR_SRC = REPO / "renode" / "sensor.py"
DEFAULT_OUT = REPO / "build" / "gen"

PLATFORM_TEMPLATE = """// GENERATED by tools/gen_run.py - do not edit.
// Seed for this run: {seed}

using "platforms/boards/stm32f4_discovery.repl"

// The stock STM32F4 model has no DWT block, so the recorder would have no
// timestamp source. CYCCNT is what every trace entry is stamped with.
dwt: Miscellaneous.DWT @ sysbus 0xE0001000
    frequency: 168000000

// The simulated world: two registers the firmware cannot predict.
//   0x50000000  depth sample (an ADC data register on real hardware)
//   0x50000004  control-timer jitter
// Seeded, so runs differ from one another on purpose - recording inside a
// deterministic simulator and replaying in the same one would prove nothing.
sensor: Python.PythonPeripheral @ sysbus 0x50000000
    size: 0x8
    initable: true
    filename: "{sensor_path}"
"""


def render_sensor(seed: int) -> str:
    src = SENSOR_SRC.read_text(encoding="utf-8")
    patched, count = re.subn(
        r"^SEED = .*$", f"SEED = {seed}", src, count=1, flags=re.MULTILINE
    )
    if count != 1:
        raise SystemExit(
            f"{SENSOR_SRC}: expected exactly one 'SEED = ...' line, found {count}"
        )
    _require_ascii(SENSOR_SRC, patched)
    return patched


def _require_ascii(source: pathlib.Path, text: str) -> None:
    """Renode runs peripheral scripts under IronPython, which follows Python 2
    rules and refuses non-ASCII source. A stray em dash in a comment fails the
    whole platform at machine-creation time with an error that points at the
    generated file rather than the one you edited, so it is caught here."""
    try:
        text.encode("ascii")
    except UnicodeEncodeError as exc:
        offending = text[exc.start : exc.end]
        line = text.count("\n", 0, exc.start) + 1
        raise SystemExit(
            f"{source}:{line}: non-ASCII character {offending!r}. "
            "Renode's IronPython rejects it; keep peripheral scripts ASCII-only."
        ) from exc


# Renode monitor scripts comment with '#'. The '//' form belongs to .repl
# platform files; using it here aborts the whole include with a tokenizer error
# and leaves you with a machine that was never created.
RESC_TEMPLATE = """# GENERATED by tools/gen_run.py - do not edit.
# Seed for this run: {seed}
mach create "rewind-m-{seed}"
machine LoadPlatformDescription @{platform}
sysbus LoadELF @{elf}
sysbus.usart2 CreateFileBackend @{uart_out}
{oracle}emulation RunFor "{run_for}"
quit
"""

# Ground-truth recording, from outside the CPU. Renode hooks take a single line
# of Python, so these are written to need nothing else: no shared state, no
# helper functions, and no backslashes (the monitor tokenises the line before
# Python ever sees it, and an escape would not survive).
#
# Opening the file per event is not fast. It does not need to be: a run produces
# a few hundred events, and the oracle is not the thing whose cost is measured.
ORACLE_TEMPLATE = """# Ground truth for the differential check - see docs/TRACE-FORMAT.md
sysbus SetHookAfterPeripheralRead sysbus.sensor "open(r'{oracle_out}','a').write(('S %d' if offset == 0 else 'J %d') % value + chr(10))"
sysbus.cpu AddHookAtInterruptBegin "open(r'{oracle_out}','a').write('I %d' % exceptionIndex + chr(10))"
"""

DEFAULT_ELF = REPO / "firmware" / "build" / "rewind-m.elf"


def generate(seed: int, out_dir: pathlib.Path) -> pathlib.Path:
    out_dir.mkdir(parents=True, exist_ok=True)

    sensor_path = out_dir / f"sensor_{seed}.py"
    sensor_path.write_text(render_sensor(seed), encoding="utf-8")

    platform_path = out_dir / f"rewind_{seed}.repl"
    platform_path.write_text(
        PLATFORM_TEMPLATE.format(
            seed=seed,
            # Forward slashes work on both platforms; backslashes would need
            # escaping inside the .repl string literal.
            sensor_path=sensor_path.as_posix(),
        ),
        encoding="utf-8",
    )
    return platform_path


def generate_resc(
    seed: int,
    out_dir: pathlib.Path,
    uart_out: pathlib.Path,
    run_for: str = "0.5",
    elf: pathlib.Path | None = None,
    oracle_out: pathlib.Path | None = None,
) -> pathlib.Path:
    """Emit a headless run script for one seed.

    Used by the campaign runner, which needs thousands of runs and cannot pay
    Robot Framework's per-suite startup cost.
    """
    # Every path in the script is made absolute. Renode resolves `@path` against
    # its own installation root rather than the working directory, so a relative
    # path here silently points somewhere nobody intended.
    out_dir = out_dir.resolve()
    platform_path = generate(seed, out_dir).resolve()
    elf_path = (elf or DEFAULT_ELF).resolve()
    if not elf_path.exists():
        raise SystemExit(f"{elf_path}: not built. Run `make -C firmware` first.")

    oracle_block = ""
    if oracle_out is not None:
        oracle_block = ORACLE_TEMPLATE.format(
            oracle_out=oracle_out.resolve().as_posix()
        )

    resc_path = out_dir / f"run_{seed}.resc"
    resc_path.write_text(
        RESC_TEMPLATE.format(
            seed=seed,
            platform=platform_path.as_posix(),
            elf=elf_path.as_posix(),
            uart_out=uart_out.resolve().as_posix(),
            run_for=run_for,
            oracle=oracle_block,
        ),
        encoding="utf-8",
    )
    return resc_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--out-dir", type=pathlib.Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    platform_path = generate(args.seed, args.out_dir)
    print(platform_path.as_posix())
    return 0


if __name__ == "__main__":
    sys.exit(main())
